### ISSUE TITLE
nginx-Container liefert 403/forbidden beim Aufruf 

### ISSUE THREAD

**Issue by designzwang** [54GradSoftware/tracker-checker#14]
Hallo,

die README erweckt den Eindruck, als ob es eine lauffähige Umgebung zum Check der Fonts ist ...  ist es nicht so gedacht?

Nach Anpassung des Compose-Files (einzige Änderung war ein anderer exposed Port anstelle der 8080 ) und docker-compose -up starten alle Container ohne Fehler, aber der Aufruf des Root-URLs führt zu einem 403er, ebenso der Aufruf  mit url=...-Parameter.

```
diff docker-compose.yml docker-compose.yml.example
<       - "8088:8080"
---
>       - "8080:8080"
```

http://(DOCKERHOST):8088/  --> 403
http://(DOCKERHOST):8088/?url=.....  --> 403

Log des nginx-Containers:
```
2022/10/31 11:25:53 [error] 25#25: *3 directory index of "/var/www/html/" is forbidden, client: 172.17.84.194, server: _, request: "GET /?url=https://www.microsoft.com/ HTTP/1.1", host: "www.koeln.dev04:8088"
172.17.84.194 - - [31/Oct/2022:11:25:53 +0000] "GET /?url=https://www.microsoft.com/ HTTP/1.1" 403 37 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:106.0) Gecko/20100101 Firefox/106.0"
```

Hab ich da was übersehen, oder fehlt noch was in der README bezüglich Start/Aufruf ?

VG
Uli

**Comment by adb-sh** [comment]
Moin, vielleicht musst du zunaechst getrennt das frontend builden. Proiere dazu:
```
docker-compose -p gfc down
docker-compose -p gfc up frontend
dokcer-compose -p gfc up backend worker redis nginx -d --scale worker=4
```
Das kommt daher, dass der Build-Prozess dess Frontends erst beim starten des stacks gebuilded wird und der build orderner ggf. noch nicht existiert und nicht im nginx gemounted werden kann. Nginx gibt dann 403 zurueck.

**Comment by adb-sh** [comment]
Hey :) Ich habe den build-Prozess angepasst.
Es werden nun eigenstaendige docker-images gebaut, und nicht einfach nur ein volume eingehangen.
Du kannst wie gewohnt den `docker-compose up` Befehl nuzten.
Solltest du allerdings eine neue version bauen wollen, solltest du zusaetzlich den flag `--build` setzen.
z.B.:
```
docker-compose -p gfc up -d --build
```

**Comment by designzwang** [comment]
@adb-sh  : Bingo - jetzt geht es "out of the box" 
Ich war auf der Suche nach einer Lösung, die die gescannten Domainnamen nicht public bzw an Dritte bekanntgibt, daher ist es sehr hilfreich, es  lokal laufenlassen zu können. Danke fürs Bereitstellen dieser Lösung!

Gruss
Uli
