### ISSUE TITLE
Ich möchte eine Englische und Deutsche Variante für den Google Font Checker haben

### ISSUE THREAD

**Issue by scammo** [54GradSoftware/tracker-checker#3]

**Comment by adb-sh** [comment]
- add multi-language; add PWA manifest.json 33bc72c146dcf2012102cb3dfc51621638172027
- debug multi-language detection d64d9091e401e8dae06dfe68d8d32c9f649e1a16
- add language switch c3f7c6df7b1c7fe230298e7a771212f7222c5457
