### ISSUE TITLE
Massenabfrage von Domains

### ISSUE THREAD

**Issue by CarstenHager** [54GradSoftware/tracker-checker#8]
Nachdem das Thema gerade etwas aktuer wird, wollte ich alle mein Kundendomains prüfen.
Aber 250 Domains per Hand eingeben war etwas mühsam.

Würde die Möglichkeit bestehen, mehrere Domains gleichzeitig zu prüfen?

Vielen dank für eure Arbeit bisher.

**Comment by scammo** [comment]
@CarstenHager Danke für die Idee. Ist aber erstmal nicht geplant weil das ein wenig den Umfang des Tools sprengt. Wenn du die API Kommerziell nutzen möchtest kannst du uns gerne unter sbrinkmann@54gradsoftware.de erreichen.
